name:                api
version:             0.1.0.0
github:              "smaccoun/api"
license:             BSD3
author:              "Steven MacCoun"
maintainer:          "theraccoun@gmail.com"
copyright:           "2018 Steven MacCoun"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/smaccoun/api#readme>

default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- RecordWildCards
- NamedFieldPuns
- DeriveGeneric
- DuplicateRecordFields
- TypeOperators
- DataKinds

dependencies:
- base >= 4.7 && < 5
- protolude
- text
- aeson
- attoparsec
- word8
- wai
- warp
- servant
- servant-server
- transformers
- fast-logger
- natural-transformation
- mtl
- wai-cors
- wai-extra
- data-default
- selda
- selda-postgresql
- postgresql-libpq
- resource-pool

library:
  source-dirs: src

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api


tests:
  api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
