resolver: lts-9.4

# User packages to be built.
# Various formats can be used as shown in the example below.
#
packages:
   extra-dep: true

packages:
- .
- location:
    git: https://github.com/tathougies/beam.git
    commit: 03f1091b0e0e05a76ec622e454e0c95a7195fb25
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres

extra-deps:
- servant-0.11
- servant-server-0.11
- foundation-edge-0.0.3

flags: {}

extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.6"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
