resolver: lts-9.4

ghc-options:
  api: -Wall -Werror -O0 -fwarn-tabs -fno-warn-orphans

packages:
   extra-dep: true

packages:
- .
- location:
    git: https://github.com/tathougies/beam.git
    commit: 03f1091b0e0e05a76ec622e454e0c95a7195fb25
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres

extra-deps:
- servant-0.11
- servant-server-0.11
- foundation-edge-0.0.3
- servant-auth-0.3.1.0
- servant-auth-server-0.3.2.0
- servant-auth-swagger-0.2.9.0

flags: {}

extra-package-dbs: []
