version: 2

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-9.4

    steps:
      - checkout

      - run:
          name: deploy
          no_output_timeout: 120m
          command: |
            docker build --rm=false - t "$DOCKER_DIR" -f Dockerfile .
            docker push  "$DOCKER_DIR"




workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
