version: 2

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-11.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - stack-{{ .Branch }}-{{ checksum "./back-end/stack.yaml" }}

      - run:
          name: build_api
          command: |
            ls -la
            ls -la ~/.stack
            mkdir -p /opt/build
            cp -r ./back-end/* /opt/build
            cd /opt/build
            ls
            stack setup
            stack build

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: install docker
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: containerize_build
          command: |
            cd /opt/build
            ls -la
            docker build --rm=false -t smaccoun/hasm-elm-example:latest -f DockerfileExe .

      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "./back-end/stack.yaml" }}
          paths:
            - ~/.stack
            - ./back-end/.stack-work

      - run:
          name: install_pip
          command: |
            sudo apt-get update
            sudo apt-get -y install python-pip
            sudo apt-get install python-dev
            pip install --upgrade botocore

      - run:
          name: install_awscli
          command: sudo apt-get -y install awscli

      - run:
          name: install_awsebcli
          command: pip install --upgrade --user awsebcli

      - run:
          name: deploy
          command: |
            docker image ls
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push smaccoun/hasm-elm-example:latest


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
