version: 2

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-9.4

    steps:
      - run:
          name: deploy
          no_output_timeout: 120m
          command: |
            ./deploy-staging.sh $CIRCLE_SHA1




workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
